### ISSUE TITLE
[PHPUnit DISCUSSÃO]

### ISSUE THREAD

**Issue by Fredrumond** [Fredrumond/myestoque#10]
@mrprompt estou usando como referencia para estudo de tdd os artigos que voce mandou no slack, porem estou com problemas.... estou seguindo [esse artigo](https://tableless.com.br/phpunit-como-iniciar-sem-dores/) mas não consigo passar da criação da classe Math. Não sei se seria um problemas nos namespaces...você teria alguma sugestão? 

**Classe PHPNativeElementsTest**
```
use PHPUnit_Framework_TestCase as PHPUnit;
use Application\NativeElements\Math;

class PHPNativeElementsTest extends PHPUnit {
    
    protected $math;


    public function setUp() {
        //Parametros de inicialização, executa antes de cada teste
        $this->math = new Math;
    }
    
    public function testOperacaoMatematica() {
        $this->assertEquals(3, $this->math->sum(1,2), 'Nao somou corretamente');
    }
    
    public function tearDown() {
        //Parametros de finizalização, executa apos a finalizaçã de casa teste
    } 
}
```
**Classe Math**
```
<?php
namespace Application\NativeElements;                      

class Math {
    
}

```

E o erro continua travando o teste na linha **13 que é $this->math = new Math;** falando que não tem a classe e ja criei a classe, estou meio perdido aqui.

**Comment by mrprompt** [comment]
Se você já criou a classe, talvez o problema seja no mapeamento dos namespaces mesmo.

**Comment by Fredrumond** [comment]
E existe uma maneira de verificar o mapeamento dos namespaces?

**Comment by mrprompt** [comment]
Olha isso: https://jtreminio.com/2012/10/composer-namespaces-in-5-minutes/

Vê se ajuda.

**Comment by Fredrumond** [comment]
Olhei o artigo e fiquei foi mais confuso ainda kkkkk

Realizei um teste maluco aqui se era erro no namespace e nao era pq criei um construtor pra exibir uma msg na tela no meu teste e funcionou tranquilamente. É foda quando nao acha o que ta bugando a parada, da uma agonia.
````
<?php

define("DS", DIRECTORY_SEPARATOR);
require __DIR__ . DS . 'vendor' . DS . 'autoload.php';

use Application\NativeElements\Math;

$test = new Math();
````

**Comment by mrprompt** [comment]
Depois que edita o composer.json, tem que dar um composer update, ou no caso de namespaces, apenas um composer dump-autoload para atualizar.

Outra coisa que tu tem que checar, o namespace é basado em diretórios, tu criou a classe Math em src/NativeElements/Math.php ?

**Comment by Fredrumond** [comment]
Ta tudo certinho. A estrutura ta igual mostrada na figura abaixo
![image](https://cloud.githubusercontent.com/assets/6002655/20929865/a281c63c-bbb2-11e6-85d9-a9e05e84856e.png)

To pelejando aqui pra achar onde ta a navalhada kkk se quiser dar uma olhada [aqui](https://github.com/Fredrumond/PHPUnit) subi o código pra ficar mais fácil de você olhar.

**Comment by mrprompt** [comment]
Clonei aqui e funcionou corretamente cara.

Os passos:

```
git clone git@github.com:Fredrumond/PHPUnit.git fred-phpunit
composer install
phpunit tests/PHPNativeElementsTest.php
```

Como você pode ver, nada demais..
Faz o seguinte, remove a tua pasta vendor e roda o ```composer install``` novamente pra ver.

**Comment by mrprompt** [comment]
Seria bom também colocar um arquivo phpunit.dist.xml na raiz do projeto.

**Comment by Fredrumond** [comment]
Ta foda mano, nao quer passar por nada, ate fiz tudo de novo. Como eu to usando o win sera que é algo que deixei pra trás na hora de configurar? Acho que nao.....ultima tentativa vai ser reiniciar a maquina, se nao der complicou.

![image](https://cloud.githubusercontent.com/assets/6002655/20935286/3c8c9ea2-bbc5-11e6-9c55-35f3f9973268.png)

O que seria o ````arquivo phpunit.dist.xml```` ?

**Comment by mrprompt** [comment]
Tá, windão eu não saco nada mesmo... fosse tu botava uma VM aí.

O xml é um arquivo de configuração default do phpunit, serve para configurar o bootstrap dele, como onde estão os testes, logs e etc.

**Comment by Fredrumond** [comment]
Minha VM fui atualizar o PHP pra versão 7, deu foi zebra kkk fudeu foi tudo la. É uma VM usando Debian 7. Vou ter que montar outra pq nao to sabendo resolver. Indica alguma melhor pra montar? Ubuntu? Ou fica no debian mesmo?

Vou dar uma olhada nesse esquema do xml depois

**Comment by mrprompt** [comment]
Faz por aqui ó: https://puphpet.com/

;)

**Comment by Fredrumond** [comment]
Cara antes de você me mandar o link eu ja tava aqui com ele aberto tentando entender kkkkk

**Comment by mrprompt** [comment]
Booooa

**Comment by Fredrumond** [comment]
Ta instalando aqui, sai configurando tudo maluco, pq eu realmente nao to entendo nada. Sei nem como que usa kkkkk

**Comment by gusttavoaguiarr** [comment]
Pq não utiliza docker?

**Comment by mrprompt** [comment]
Pô, já que não usas nem Docker nem Vagrant e vais ter que ler a respeito, começa pelo Docker mano, bem mais rápido e também mais fácil :)

**Comment by mrprompt** [comment]
Docker para Windows: https://docs.docker.com/docker-for-windows/

**Comment by Fredrumond** [comment]
Vou recomeçar tudo entao pelo docker. Pq to a horas aqui tomando pancada de todo lado do vagrant

**Comment by Fredrumond** [comment]
@mrprompt @gusttavoaguiarr muito obrigado pelas dicas ai, vou estudar o docker depois, porque tentei agora e nao consegui, cheguei ja no ponto do dia que a cabeça da aquela travada.

Bom eu nao ia terminar os estudos por hoje sem conseguir rodar um teste, e eu consegui. Nao fiz naquela maneira do inicio da conversa fiz simplesmente um arquivo nesse estilo maluco ai de baixo. Seria muito errado fazer testes assim?
````
<?php 

class ListaTest extends PHPUnit_Framework_TestCase{
	public function testQualquerCoisa(){
		$lista = array();
		$this->assertEquals(0,count($lista));
	}
}
````
Onde eu queria verificar se o array tava vazio ou nao. Colocando 1 ele falhou colocando 0 ele passou bacana.
![image](https://cloud.githubusercontent.com/assets/6002655/20944980/a5d24f02-bbec-11e6-9153-5210bdb01a44.png)

Agora fica minha duvida aqui no ar, porque sera que da outra maneira nao rodou nem a pau na minha maquina e no @mrprompt rodou beleza quando ele clonou? Mais um misterio kkkkkk se alguem tiver algum conhecido que usa o windao da massa pra desenvolver marca ele aqui, nao vou ficar quieto enquanto nao descobrir isso. Conheço uma galera que desenvolve super bem no windao, mas os que eu perguntei nunca usaram o phpUnit pra salvar essa duvida.

**Comment by gusttavoaguiarr** [comment]
@Fredrumond talvez eu consiga te ajudar um pouco com docker, eu só venho trabalhando com docker mas ainda to nooob :( mas qualquer coisa me chame 💃 se eu não souber responder procuramos juntos. Sobre a questão do windows, se eu fosse vc eu já trocava para alguma distribuição Linux, trabalhei por um tempo com windows e cara depois que eu troquei para linux foi uma das melhores coisas que já fiz mas enfim gostei da iniciativa do TDD, infelizmente ainda não trabalho com TDD e nunca pratiquei :( MAS pretendo  em breve e cara não hesite em me chamar :D, qualquer coisa to no slack

**Comment by mrprompt** [comment]
Então cara, na real esse teu teste não faz nada, tu só provou que o phpunit tá instalado kkk..

A diferença é só que, como tu não carregou os namespaces, não está carregando os testes. Tenta fazer o seguinte, copia o phpunit.dist.xml de algum projeto meu, que esteja carregando o autoload.php do vendor e tenta novamente, pode ser por isso que teus testes anteriores não estavam carregando, afinal, não estava achando a classe - e isso é culpa do autoloader.

Sobre funcionar no windows, eu realmente não sei e nem tenho uma máquina aqui rodando ele pra investigar. De qualquer forma, acho que tu rodando no Docker, com um Linux vai funcionar de boa.

**Comment by Fredrumond** [comment]
Ae @mrprompt @gusttavoaguiarr consegui rodar o vagrant de boas aqui com esse [repositorio](https://github.com/EspecializaTi/vagrant-setup-php) foi muito simples, agora tenho so que atualizar a versao do php dele pra 7.0. 

Alguem ai consegue me dizer se eu usar esses comandos aqui consigo instalar de boa?  Nao to querendo fuder a maquina de novo kkk

````
sudo apt-get install python-software-properties
sudo add-apt-repository ppa:ondrej/php-7.0
sudo apt-get update
sudo apt-get purge php5-fpm
sudo apt-get install php7.0-cli php7.0-common libapache2-mod-php7.0 php7.0 php7.0-mysql php7.0-fpm php7.0-curl php7.0-gd php7.0-bz2
````

**Comment by mrprompt** [comment]
Show que conseguiu cara. Então, teoricamente tá tudo certo, manda bala. Não deixa de adicionar a extensão xdebug no PHP, ajuda bastante :)
