### ISSUE TITLE
Remover nbproject

### ISSUE THREAD

**Issue by mrprompt** [Fredrumond/myestoque#3]
O nbproject não precisa ficar no projeto, podendo ser colocad no .gitignore

**Comment by Fredrumond** [comment]
Solucionado com o tutorial da pagina: https://fjorgemota.com/gitignore-ou-como-ignorar-arquivos-no-git/

**Comment by mrprompt** [comment]
Então está faltando dar push, pq continua no repositório.

**Comment by Fredrumond** [comment]
Realmente a pasta ainda nao saiu
