### ISSUE TITLE
Composer

### ISSUE THREAD

**Issue by mrprompt** [Fredrumond/myestoque#4]
Adicionar o composer para gerenciar as futuras dependências do projeto.

**Comment by Fredrumond** [comment]
Resolvido com ajuda do tutorial: http://tableless.com.br/composer-para-iniciantes/

**Comment by mrprompt** [comment]
Cade o composer.json e composer.lock? Eles devem ficar no repositório.

**Comment by Fredrumond** [comment]
não estou conseguindo da o push...ta dando um erro. Vou tentar olhar o que é
![image](https://cloud.githubusercontent.com/assets/6002655/20720348/ed68f782-b645-11e6-8071-a349a02164ab.png)

**Comment by Fredrumond** [comment]
Esqueci de dar um pull quando alterei o readme. Tudo certo.
